export const qk = {
  health: ["health"] as const,
  systemHealth: ["system", "health"] as const,
  regimeReport: ["regime-report"] as const,
  dashboardState: ["dashboard-state"] as const,
  aiReport: ["ai-report"] as const,
  paperTradingState: ["paper-trading", "state"] as const,
  marketSessions: ["market-sessions", "current"] as const,
  marketSessionAsset: (symbol: string) =>
    ["market-sessions", "asset", symbol] as const,
  assetRegistry: ["assets", "registry"] as const,
  assetAnalysis: (symbol: string) => ["analysis", "asset", symbol] as const,
  technicalInsight: (symbol: string) =>
    ["technical", "insight", symbol] as const,
  learningSummary: ["learning", "summary"] as const,
  dataSnapshot: ["data", "snapshot"] as const,
  rebalanceProposal: ["learning", "rebalance"] as const,
  calibration: ["learning", "calibration"] as const,
  tfWeights: ["learning", "tf-weights"] as const,
  mistakes: ["learning", "mistakes"] as const,
  riskCorrelation: ["risk", "correlation"] as const,
  riskHalts: ["risk", "halts"] as const,
  decisionMatrix: ["decision", "matrix"] as const,
  agentMatrix: ["technical", "agent-matrix"] as const,
  shadowComparison: ["decision", "shadow"] as const,
  cockpitBrief: ["cockpit", "brief"] as const,
  replayStatus: ["replay", "status"] as const,
  replayBacktest: ["replay", "backtest"] as const,
  replaySnapshot: (snapshotId: string) => ["replay", "snapshot", snapshotId] as const,
  replayDecisionTrace: (snapshotId: string) =>
    ["replay", "decision-trace", snapshotId] as const,
  tradeTickets: ["paper-trading", "tickets"] as const,
  notifications: ["notifications"] as const,
  agentBriefing: ["agent", "briefing"] as const,
  liquidityRotation: ["liquidity", "rotation"] as const,
  pendingOrders: ["paper-trading", "orders"] as const,
};
