export const qk = {
  health: ["health"] as const,
  regimeReport: ["regime-report"] as const,
  dashboardState: ["dashboard-state"] as const,
  aiReport: ["ai-report"] as const,
  paperTradingState: ["paper-trading", "state"] as const,
  learningSummary: ["learning", "summary"] as const,
  dataSnapshot: ["data", "snapshot"] as const,
  rebalanceProposal: ["learning", "rebalance"] as const,
  calibration: ["learning", "calibration"] as const,
  mistakes: ["learning", "mistakes"] as const,
  riskCorrelation: ["risk", "correlation"] as const,
  riskHalts: ["risk", "halts"] as const,
  decisionMatrix: ["decision", "matrix"] as const,
  cockpitBrief: ["cockpit", "brief"] as const,
  replayStatus: ["replay", "status"] as const,
};
