"""Env değişkenleri defteri (temizlik B9) — kodun okuduğu HER env adı burada.

tests/contract/test_env_registry.py kodu tarar: kayıtsız bir env okuması ya da
artık okunmayan bir kayıt testi kırar. Yeni env eklemek bilinçli bir adım olsun;
"bu flag açık mı?" sorusunun cevabı için türüne göre nereye bakılacağı aşağıda.

Değerler burada TUTULMAZ (eskiyen kopya yasağı); yalnız ad → tür.
"""
from __future__ import annotations

KINDS = {
    "behavior": "Öğrenme/karar davranışını değiştiren owner flag'leri. AWS değeri: scripts/deploy-from-github.sh (ensure_env); lokal: .env; sapma: scripts/flag-sync-check.sh.",
    "runtime": "Süreç/port/aralık/boyut ayarları (davranışa dokunmaz).",
    "provider": "Veri/LLM/TTS sağlayıcı ayarları (URL, model, TTL).",
    "secret": "Anahtarlar — yalnız .env / sunucu ortamı; repoya asla yazılmaz.",
    "test": "Test/fixture anahtarları — canlıda kapalı olmalı (runtime'da mock yok).",
    "path": "Runtime dosya yolları (data/runtime altı varsayılan; testler izole eder).",
}

REGISTRY: dict[str, str] = {
    # ── behavior
    "ACTIVATION_MIN_OUTCOMES": "behavior",
    "ACTIVATION_MONITOR_MAX_AGE_HOURS": "behavior",
    "BACKTEST_CHALLENGER_ENABLED": "behavior",
    "BACKTEST_RECON_ENABLED": "behavior",
    "BAR_HISTORY_ENABLED": "behavior",
    "DISCOVERY_SCAN_ENABLED": "behavior",
    "EXIT_FORENSICS_NUDGE": "behavior",
    "EXPECTANCY_R_MODE": "behavior",
    "GUARD_AUTO_DISABLE": "behavior",
    "GUARD_MONITOR_MAX_AGE_HOURS": "behavior",
    "GUARD_ROLLBACK_MIN_OUTCOMES": "behavior",
    "LEARNING_ADVISOR_APPLY": "behavior",
    "MISTAKE_MEMORY_V2": "behavior",
    "REBALANCE_AUTO_APPLY": "behavior",
    "REBALANCE_AUTO_APPLY_BAND": "behavior",
    "REBALANCE_MONITOR_MAX_AGE_HOURS": "behavior",
    "REBALANCE_ROLLBACK_MIN_OUTCOMES": "behavior",
    "SUBSIGNAL_SCORECARD_ENABLED": "behavior",
    "TF_CALIBRATION_AUTO_ONLY": "behavior",
    "TF_SCORING_V2_SHADOW": "behavior",
    "TF_TARGET_AUTO_ONLY": "behavior",
    "TF_TARGET_EDGE_GATE": "behavior",
    "TF_TARGET_MIN_NEW": "behavior",
    "TF_TARGET_MONITOR_MAX_AGE_HOURS": "behavior",
    "TF_TARGET_ROLLBACK_MIN_OUTCOMES": "behavior",
    "TF_TARGET_TRAIL_AUTOTUNE": "behavior",
    "TF_TRUST_PER_BUCKET": "behavior",
    "THRESHOLD_AUTOTUNE": "behavior",
    "THRESHOLD_ROLLBACK_MIN_OUTCOMES": "behavior",
    "WEIGHT_LOSS_AWARE": "behavior",
    "WEIGHT_REGIME_FILTER": "behavior",
    # ── runtime
    "API_HOST": "runtime",
    "API_PORT": "runtime",
    "BACKTEST_CHALLENGER_INTERVAL_SEC": "runtime",
    "CORS_EXTRA_ORIGINS": "runtime",
    "COUNCIL_SCORECARD_INTERVAL_SEC": "runtime",
    "DEV_CORS": "runtime",
    "DISCOVERY_SHADOW_MAX_MB": "runtime",
    "EXIT_BACKTEST_INTERVAL_SEC": "runtime",
    "LEARNING_BUDGET_MS": "runtime",
    "LEARNING_INTERVAL_SEC": "runtime",
    "NO_EXECUTION": "runtime",
    "PAPER_ONLY": "runtime",
    "RUN_WORKERS": "runtime",
    "SHADOW_LOG_MAX_MB": "runtime",
    "SNAPSHOT_STORE_MAX": "runtime",
    "SUBSIGNAL_SCORECARD_INTERVAL_SEC": "runtime",
    "TICK_INTERVAL_SEC": "runtime",
    "WORLD_STATE_ARCHIVE_MAX": "runtime",
    "ZERO_TWO_STRATEGY_INTERVAL_SEC": "runtime",
    "ZONE_PLAN_SHADOW_INTERVAL_SEC": "runtime",
    "ZONE_PROPOSER_INTERVAL_SEC": "runtime",
    # ── provider
    "ALPHAVANTAGE_TTL_SEC": "provider",
    "CHAT_LLM_LOCAL_FIRST": "provider",
    "COINGECKO_OHLCV_TTL_SEC": "provider",
    "COINGECKO_PRICE_TTL_SEC": "provider",
    "EDGE_TTS_VOICE": "provider",
    "ELEVENLABS_MODEL_ID": "provider",
    "ELEVENLABS_VOICE_ID": "provider",
    "FINNHUB_TTL_SEC": "provider",
    "FRED_TTL_SEC": "provider",
    "GROQ_MODEL": "provider",
    "LLM_CACHE_TTL_SEC": "provider",
    "LLM_DAILY_TOKEN_BUDGET": "provider",
    "LLM_LOAD_DOTENV": "provider",
    "LLM_MAX_TOKENS_PER_REQUEST": "provider",
    "LLM_MODE": "provider",
    "OLLAMA_API_URL": "provider",
    "OLLAMA_KEEP_ALIVE": "provider",
    "OLLAMA_MODEL": "provider",
    "OLLAMA_TIMEOUT_SEC": "provider",
    "OPENROUTER_API_URL": "provider",
    "OPENROUTER_APP_NAME": "provider",
    "OPENROUTER_MODEL": "provider",
    "OPENROUTER_SITE_URL": "provider",
    "TAVILY_LOAD_DOTENV": "provider",
    "TAVILY_MAX_RESULTS": "provider",
    "TAVILY_SEARCH_DEPTH": "provider",
    "TAVILY_SEARCH_URL": "provider",
    "TTS_PROVIDER": "provider",
    "TWELVEDATA_TTL_SEC": "provider",
    "WORLD_BRIEF_LLM_ENABLED": "provider",
    # ── secret
    "ALPHAVANTAGE_API_KEY": "secret",
    "API_AUTH_TOKEN": "secret",
    "COINGECKO_API_KEY": "secret",
    "ELEVENLABS_API_KEY": "secret",
    "FINNHUB_API_KEY": "secret",
    "FRED_API_KEY": "secret",
    "GROQ_API_KEY": "secret",
    "OPENROUTER_API_KEY": "secret",
    "TAVILY_API_KEY": "secret",
    "TWELVEDATA_API_KEY": "secret",
    # ── test
    "CALENDAR_USE_FIXTURE": "test",
    "DERIVATIVES_USE_FIXTURE": "test",
    "NEWS_USE_FIXTURE": "test",
    "OHLCV_USE_FIXTURE": "test",
    "OPTIONS_USE_FIXTURE": "test",
    "PRICE_USE_MOCK": "test",
    "TEST_USE_MOCK": "test",
    "TICK_SKIP_SIGNAL_HANDLERS": "test",
    "TICK_WORKER_DISABLE_LOCK": "test",
    # ── path
    "ACTIVATION_WATCHDOG_PATH": "path",
    "AGENT_MODE_STORE_PATH": "path",
    "BACKTEST_CHALLENGER_META_PATH": "path",
    "BACKTEST_CHALLENGER_PATH": "path",
    "BACKTEST_CHALLENGER_REPORT_PATH": "path",
    "BACKTEST_RECON_PATH": "path",
    "BAR_HISTORY_DIR": "path",
    "CALIBRATION_AUDIT_PATH": "path",
    "CALIBRATION_STORE_PATH": "path",
    "CAUSAL_CALIBRATION_PATH": "path",
    "CAUSAL_EVENT_LEDGER_PATH": "path",
    "CAUSAL_EVENT_STUDY_PATH": "path",
    "COUNCIL_SCORECARD_PATH": "path",
    "CUSTOM_ASSETS_PATH": "path",
    "DECISION_LOG_PATH": "path",
    "DISCOVERY_SCAN_PATH": "path",
    "DISCOVERY_SHADOW_PATH": "path",
    "EMPIRICAL_PWIN_PATH": "path",
    "EVENT_OUTCOMES_PATH": "path",
    "EXIT_BACKTEST_PATH": "path",
    "EXIT_FORENSICS_OUT_PATH": "path",
    "GOVERNOR_PROPOSALS_PATH": "path",
    "GUARD_MONITOR_STORE_PATH": "path",
    "GUARD_OVERRIDES_PATH": "path",
    "LEARNING_OUT_PATH": "path",
    "LEARNING_RUN_PATH": "path",
    "LLM_BUDGET_PATH": "path",
    "LLM_CACHE_PATH": "path",
    "MACRO_BACKTEST_PATH": "path",
    "MISSED_OPP_LOG_PATH": "path",
    "NEWS_FORECAST_LEDGER_PATH": "path",
    "NEWS_FORECAST_PATH": "path",
    "NEWS_EVENT_LEDGER_PATH": "path",
    "NEWS_EVENT_STUDY_PATH": "path",
    "NOTIFICATIONS_PATH": "path",
    "OHLCV_CACHE_DIR": "path",
    "PAPER_ARCHIVE_DIR": "path",
    "PAPER_AUDIT_PATH": "path",
    "PAPER_STATE_PATH": "path",
    "PHYSICAL_COMMODITIES_CONFIG_PATH": "path",
    "REBALANCE_STORE_PATH": "path",
    "REFLECTION_PATH": "path",
    "REGIME_RISK_BRAKE_PATH": "path",
    "REGIME_STATE_PATH": "path",
    "RISK_HALT_PATH": "path",
    "SCENARIOS_CONFIG_PATH": "path",
    "SECTOR_ROTATION_PATH": "path",
    "SHADOW_LOG_PATH": "path",
    "SNAPSHOT_STORE_PATH": "path",
    "TECHNICAL_BOOK_CORPUS_PATH": "path",
    "TF_CALIBRATION_OUT_PATH": "path",
    "TF_SCORING_RACE_LEDGER": "path",
    "TF_SCORING_RACE_REPORT": "path",
    "TF_SCORING_V2_SHADOW_PATH": "path",
    "TF_TARGET_AUTOAPPLY_PATH": "path",
    "TF_TARGET_PROPOSAL_OUT_PATH": "path",
    "TF_TARGET_STORE_PATH": "path",
    "TF_TARGET_TRIGGER_PATH": "path",
    "TF_WEIGHT_PROPOSAL_OUT_PATH": "path",
    "THRESHOLD_AUTOAPPLY_PATH": "path",
    "THRESHOLD_OVERRIDES_PATH": "path",
    "TICKETS_PATH": "path",
    "TICK_WORKER_LOCK_PATH": "path",
    "WEIGHTS_MANIFEST_PATH": "path",
    "WEIGHTS_OUTPUT_DIR": "path",
    "WEIGHT_AUTOAPPLY_PATH": "path",
    "WORKER_HEARTBEAT_PATH": "path",
    "WORLD_GRAPH_CONFIG_PATH": "path",
    "WORLD_STATE_ARCHIVE_PATH": "path",
    "ZERO_TWO_STRATEGY_PATH": "path",
    "ZONE_PLANS_PATH": "path",
    "ZONE_PLAN_SHADOW_PATH": "path",
    "ZONE_PROPOSER_PATH": "path",
    "ZONE_PROPOSER_PATH_CFG": "path",
    "ZONE_VERDICTS_PATH": "path",
}


def names(kind: str) -> list[str]:
    """Bir türdeki env adları (sıralı)."""
    return sorted(n for n, k in REGISTRY.items() if k == kind)


__all__ = ["KINDS", "REGISTRY", "names"]
